// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq3l79te_cPl7j9mNWvuB3ocn6cY8d72E',
    appId: '1:540082182208:web:1de7b751a1b730a46fa7a5',
    messagingSenderId: '540082182208',
    projectId: 'laporpak-fp',
    authDomain: 'laporpak-fp.firebaseapp.com',
    storageBucket: 'laporpak-fp.firebasestorage.app',
    measurementId: 'G-G1DGBCZDT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR6l_uuZ-TxIm_HiGLIjgKyKu9pbW3GgU',
    appId: '1:540082182208:android:0950c26e46cac3bd6fa7a5',
    messagingSenderId: '540082182208',
    projectId: 'laporpak-fp',
    storageBucket: 'laporpak-fp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB17PUeW3SelZGCN0A1FHff906iI0A52yM',
    appId: '1:540082182208:ios:72d506383f0a1b016fa7a5',
    messagingSenderId: '540082182208',
    projectId: 'laporpak-fp',
    storageBucket: 'laporpak-fp.firebasestorage.app',
    iosBundleId: 'com.example.laporpakFp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB17PUeW3SelZGCN0A1FHff906iI0A52yM',
    appId: '1:540082182208:ios:72d506383f0a1b016fa7a5',
    messagingSenderId: '540082182208',
    projectId: 'laporpak-fp',
    storageBucket: 'laporpak-fp.firebasestorage.app',
    iosBundleId: 'com.example.laporpakFp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq3l79te_cPl7j9mNWvuB3ocn6cY8d72E',
    appId: '1:540082182208:web:c2b02116a799720a6fa7a5',
    messagingSenderId: '540082182208',
    projectId: 'laporpak-fp',
    authDomain: 'laporpak-fp.firebaseapp.com',
    storageBucket: 'laporpak-fp.firebasestorage.app',
    measurementId: 'G-5CXZJHBK99',
  );
}
